# Generated by Django 4.1.7 on 2023-03-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User_Account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "User"},
        ),
    ]
